spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/skyscanner;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

  messages:
    basename: messages,exceptions

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  dir: /Users/